### ISSUE TITLE
Adding additional sensors

### ISSUE THREAD

**Issue by B-Hartley** [unlobito/ha-hildebrandglow#12]
Hi,

Are you intending to add additional sensors to this?
I’ve got a node red flow I found in the Glow forum that displays:
Elec Meter
Gas Meter
Demand Power
Export Power
Grid Power

It would be great if you could expand the sensors to add these in.

I’m assuming you already know where this data is in the JSON, but If you need me to point you to the node red flow or the maths in it to obtain the values please let me know.

Thanks very much for developing this.
I’d much prefer to use it from a custom component, rather than having node-red running , just for this.

**Comment by unlobito** [comment]
Heya, thanks for trying out the integration!

I'm planning on adding historical electric/gas meter readings as part of #10 but I'd be interested in exposing some of the other details you've mentioned.

I'm actually not aware of the Node-RED flow you're referring to (or even of the existence of a Glow forum), but I'd be keen to take a look at the resources you've mentioned. All of the endpoints mentioned are documented by Hildebrand, but it can't hurt to see a known-working example of accessing these details :)

**Comment by B-Hartley** [comment]
The Node Red flow, splits the data out like this:

```
var elec = msg.payload.elecMtr;
var gas = msg.payload.gasMtr;
var eMetering = elec["0702"];
var watth = parseInt(eMetering["00"]["00"], 16);
var hexdemand = eMetering["04"]["00"];
if (hexdemand.length % 2 !==0) {
        hex = "0" + hexdemand;
    }
    var num = parseInt(hexdemand, 16);
    var maxVal = Math.pow(2, hexdemand.length / 2 * 8);
    if (num > maxVal / 2 - 1) {
        num = num - maxVal
    }
var idemand = num;
var iexport = 0;
if(idemand < 0) {
    iexport = -(idemand);
    idemand = 0;}
var out = parseInt(eMetering["00"]["01"], 16);
var curgas = parseInt(gas["0702"]["00"]["00"], 16);
msg.payload = {
    "current":watth,
    "export":out,
    "idemand":idemand,
    "iexport":iexport,
    "isigned":idemand - iexport,
    "cgas": curgas
};
return msg;
```

Another similar one was....

```
var elec = msg.payload.elecMtr;
var gas = msg.payload.gasMtr;
var eMetering = elec["0702"];
var watth = parseInt(eMetering["00"]["00"], 16);
var idemand = parseInt(eMetering["04"]["00"], 16);
var iexport = 0;
if(idemand > 0x80000000) {
    iexport = -(idemand - 0x100000000);
    idemand = 0;
}
var out = parseInt(eMetering["00"]["01"], 16);
var curgas = parseInt(gas["0702"]["00"]["00"], 16);
msg.payload = {
    "current":watth,
    "export":out,
    "idemand":idemand,
    "iexport":iexport,
    "isigned":idemand - iexport,
    "cgas": curgas
};
return msg;
```

**Comment by B-Hartley** [comment]
Glow forum is at:
[Glow Markt Forum](https://forum.glowmarkt.com/)

**Comment by B-Hartley** [comment]
And the Node-Red flow I'm talking about it linked from:

[Forum Post](https://forum.glowmarkt.com/index.php?p=/discussion/comment/58/#Comment_58)

at

[Google Drive - Node-Red Flow](https://drive.google.com/open?id=1Womy4C4jqZB7ZpExdfQew8RwpvnPwmpr)

**Comment by B-Hartley** [comment]
Just occurred to me that these are all based on the json you get through the mqtt channel. 
Not sure how the data from the api compares ok structure.

**Comment by ndfred** [comment]
@B-Hartley: did you try to go through Home Assistant templates? I've been using this for MQTT before and it's all native. [Here is the python code to parse it all](https://gist.github.com/ndfred/b373eeafc4f5b0870c1b8857041289a9) (pretty much exactly what you have), expressing it as templates shouldn't be that difficult.

**Comment by ndfred** [comment]
Actually as I mentioned in #14 I figured out how to get all the templates working

**Comment by unlobito** [comment]
Closed by https://github.com/unlobito/ha-hildebrandglow/releases/tag/0.2.0-beta
