### ISSUE TITLE
Add support for meter reading in addition to instant power

### ISSUE THREAD

**Issue by ndfred** [unlobito/ha-hildebrandglow#13]
This would be useful to use the [utility meter](https://www.home-assistant.io/integrations/utility_meter/) HA integration. Basically any counter expressed in kWh can then give you the daily, weekly or hourly consumption automatically. The API docs mention the `virtualentity` call returning `electricity.consumption` which is exactly what we would need.

**Comment by ndfred** [comment]
Actually #14 would be a better way to go for this as MQTT is real time while HTTP polling is not, and all the data is there

**Comment by unlobito** [comment]
Closing this as a duplicate of #14 and #12, since they cover the same functionality through different technical implementations.
