### ISSUE TITLE
Use the standard app ID

### ISSUE THREAD

**Issue by ndfred** [unlobito/ha-hildebrandglow#15]
Talking to Jane from Hildebrand support, she suggested the Glow app ID (b0f1b774-a586-4f72-9edd-27ead8aa7a8d) is really the only one they distribute right now. It would probably make sense to use that as the default and avoid asking for it in the GUI on first setup.

**Comment by G8YTZ** [comment]
Thanks for this! Saved me bothering Jane. Also @unlobito many thanks for building and publishing this integration!

Justin.
