### ISSUE TITLE
No Integration

### ISSUE THREAD

**Issue by davidjac** [unlobito/ha-hildebrandglow#18]
Have followed the HACs installation, add custom rep, restart, go to add integration but there is'nt one. Checked files in \\homeassistant\config\custom_components\hildebrandglow  all seven plus the translations folder are there. Tried reinstall  initially used V0.2 then tried Master, etc. Also tried manual install. Any ideas?

**Comment by davidjac** [comment]
OK. I found the integration available on my android app, strangely it was'nt available in Chrome on my PC. I have no idea why this may be. Assume its nothing to do with the integration.

**Comment by unlobito** [comment]
Hey @davidjac, I'm going to close this issue but feel free to reopen if you're still having problems.
