### ISSUE TITLE
No Devices / Entities created  

### ISSUE THREAD

**Issue by andynewton0** [unlobito/ha-hildebrandglow#20]
Hi 

Ive run the install a number of times and each time nothing is created.

Tried via HACS and manually , restarted HA.

checked logbook .. no errors or mention of the install.

Could you advise please ?

Thank you

**Comment by BertrumUK** [comment]
I have the same issue. I get the following error :-

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hildebrandglow/sensor.py", line 55, in async_setup_entry
    async_add_entities([sensor])
UnboundLocalError: local variable 'sensor' referenced before assignment

If I check using Postman I can pull my data 

[
    {
        "clone": false,
        "active": true,
        "veTypeId": "xxxxxxxxxxxx",
        "resources": [
            {
                "resourceId": "xxxxxxxxxxxxxxx",
                "resourceTypeId": "xxxxxxxxxxxxxx",
                "name": "gas consumption"
            },
            {
                "resourceId": "xxxxxxxxxxxxxxxx",
                "resourceTypeId": "xxxxxxxxxxxxx",
                "name": "gas cost"
            },
            {
                "resourceId": "xxxxxxxxxxxxxxxxx",
                "resourceTypeId": "xxxxxxxxxxxxxxxxxxx",
                "name": "electricity cost"
            },
            {
                "resourceId": "xxxxxxxxxxxxxxxx",
                "resourceTypeId": "xxxxxxxxxxxx",
                "name": "electricity consumption"
            }
        ],
        "ownerId": "xxxxxxxxxxxxxxxx",
        "applicationId": "xxxxxxxxxxxxxxxxx",
        "name": "DCC Sourced",
        "veChildren": [],
        "veId": "xxxxxxxxxxxxxxxx",
        "updatedAt": "2021-02-19T18:23:41.829Z",
        "createdAt": "2021-02-19T18:16:24.925Z"
    }
]

**Comment by BertrumUK** [comment]
This is the same issue

https://github.com/unlobito/ha-hildebrandglow/issues/19#issue-759491068
