### ISSUE TITLE
Version in the manifest is now a requirement for custom components

### ISSUE THREAD

**Issue by BenWoodford** [unlobito/ha-hildebrandglow#27]
Unfortunately anyone on the latest HASS version can no longer use this component (or a number of others...) as all custom components now need a version in their manifest, and will fail to load if that isn't provided

https://developers.home-assistant.io/docs/creating_integration_manifest/#version

**Comment by unlobito** [comment]
Cheers, [hassfest.yaml](https://github.com/unlobito/ha-hildebrandglow/actions/workflows/hassfest.yaml) has been annoyed about this for a while.

Fixed in 367d610, [validated](https://github.com/unlobito/ha-hildebrandglow/runs/2753364662).

**Comment by unlobito** [comment]
closed by https://github.com/unlobito/ha-hildebrandglow/releases/tag/0.1.1-beta
