### ISSUE TITLE
Hildebrand Glow Integration doesn't appear in integrations list

### ISSUE THREAD

**Issue by jasonwragg** [unlobito/ha-hildebrandglow#35]
After adding from the HAC repo the Hildebrand Glow integration doesn't appear in the integrations list.

HA Version: core-2021.6.6
Installation Type: Home Assistant Core

![Screenshot 2021-06-26 at 17 46 33](https://user-images.githubusercontent.com/53080867/123520009-78879a00-d6a6-11eb-8454-067390cc75cb.png)

**Comment by redpizza69** [comment]
+1

No "glow" integration. Rebooted twice now...
