### ISSUE TITLE
0.1.3-beta not working

### ISSUE THREAD

**Issue by danielsmith89** [unlobito/ha-hildebrandglow#44]
Just updated to 0.1.3-beta and it completely stopped all my sensors from showing any data. Rolled back to the previous version and it all works again correctly - looks like a bug in the latest version.

Thanks.

**Comment by unlobito** [comment]
Hey @danielsmith89, thanks for writing in.

Do you see any errors reported in Home Assistant's logs? You can find these at https://my.home-assistant.io/redirect/logs/

**Comment by danielsmith89** [comment]
I think it must have just been a blip, working fine now! Thanks
