### ISSUE TITLE
Home-Assistant Energy Dashboard

### ISSUE THREAD

**Issue by richard-scott** [unlobito/ha-hildebrandglow#45]
Are there any plans to add support for the Energy Dashboard?
I'm unable to see the DCC devices in the dropdown when setting up the energy dashboard it suggests more info on this page:

https://www.home-assistant.io/more-info/statistics/
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by eperdeme** [comment]
There any alternative plugins that provide this ?

**Comment by jamiewhitham** [comment]
I would like this too. It seems the Energy Dashboard "Add Consumption" is looking for energy in kWh rather than power in watts that we have. It says "Consumed Energy (kWh)" so might need something to integrate the watts over time.

**Comment by unlobito** [comment]
Hey @richard-scott @eperdeme @jamiewhitham, I appreciate your patience and enthusiasm with this request.

I've just released https://github.com/unlobito/ha-hildebrandglow/releases/tag/0.2.0-beta to add support for the [Home Assistant Energy Dashboard](https://www.home-assistant.io/docs/energy/electricity-grid/) for folk with a Consumer Access Device.

Please don't hesitate to write in if you have any issues with the upgrade

**Comment by dannytsang** [comment]
@unlobito I've just updated to 2.0 beta and my entities are not selectable for some reason or am I missing something?

Here's an example of the power consumption:
![image](https://user-images.githubusercontent.com/567982/146693136-ab9d2584-94de-4c37-b22a-efe5b7241f2b.png)
![image](https://user-images.githubusercontent.com/567982/146693154-e0306ae6-381e-4f29-a9a7-4ff02f6abc1f.png)
![image](https://user-images.githubusercontent.com/567982/146693194-3d1a49dc-984d-417f-b7dd-26f26d3d0b0b.png)

**Comment by unlobito** [comment]
Hey @dannytsang, thanks for writing in. Do you see anything under the "Energy Consumption" sensor? I made a mistake in the release notes, "Power Consumption" is for the current/instantaneous electricity use.

**Comment by dannytsang** [comment]
@unlobito I've got that one so I have added that. If I read the description right, it is an accumulative usage so would Home Assistant still be able to track per hour still?

**Comment by unlobito** [comment]
@dannytsang Yep, Home Assistant will track the changes in the counter across each hour and displays them separately

Below is a screenshot from my home installation, hovering over each bar shows a breakdown of the energy consumed during that hour

![image](https://user-images.githubusercontent.com/5637/146755580-af5a809d-3b9e-4cc3-b386-55a14edf6e02.png)

**Comment by richard-scott** [comment]
I notice I've lost my Gas readings now on this release:
<img width="1066" alt="Screenshot 2021-12-20 at 11 06 40" src="https://user-images.githubusercontent.com/5149834/146757887-86f69fc7-6030-4d28-8aad-24e8dbfcf3f9.png">

**Comment by dannytsang** [comment]
@unlobito all working my end. Thank you very much.

@richard-scott
It's working on my end. Have you checked the name of the entity because they we're renamed as part of the upgrade?

**Comment by richard-scott** [comment]
@dannytsang Ah yes, the entity with the 'eye' icon is my gas usage... but that's currently unavailable:

![Screenshot 2021-12-20 at 13 45 10](https://user-images.githubusercontent.com/5149834/146776652-cf8678d1-895c-4cab-a3e1-90f620df1eba.png)

When does that get populated/updated?

**Comment by dannytsang** [comment]
@richard-scott I think mine had the eye icon and then changed to a gas bottle. Not sure when it changed because I did restart HA and I didn't have any gas reading before it changed.

The image you have posted looks correct to me. Maybe check / post the image of the device and all its associated entities and make sure there isn't any other devices or entities that has the gas consumption? @unlobito any other suggestions?

I can't say how long it took to get a reading because our boiler was scheduled not to come on until the following day (this morning).

**Comment by richard-scott** [comment]
@dannytsang yes, I get the gas bottle icon now, but no statistics.

**Comment by dannytsang** [comment]
@richard-scott Is the entity enabled? I had to enable mine manually using the toggle in your above screenshot it looks like it's disabled (highlighted in yellow)
![image](https://user-images.githubusercontent.com/567982/146842079-98ab447d-94b1-4f79-9f65-228d1976fbd5.png)

**Comment by richard-scott** [comment]
yes, I realised that after I sent the picture and enabled it. I'll have to wait and see what data I get on the next poll as Gas values only get sent from the meter every 30min.

**Comment by unlobito** [comment]
Thanks for the clarification! I don't have a gas supply at home and am reliant on folks' feedback to test gas meter integrations, so I've opened #46 to track this as a bug.

@richard-scott I'm keen to know whether manually enabling the sensor fixed gas readings for you, though I completely agree this manual step shouldn't be necessary.

**Comment by richard-scott** [comment]
I've added a comment and a pic to #46 👍
